"""SMTP smuggling: non-standard end-of-data acceptance.

SMTP ends a message with the exact sequence ``<CR><LF>.<CR><LF>``. Several widely
deployed servers also accept looser variants — ``<LF>.<LF>``, ``<CR>.<CR>`` — and
that disagreement is exploitable. A sending server that passes the loose sequence
through verbatim, talking to a receiving server that treats it as end-of-data,
lets an attacker put a *second* message inside the body of the first.

The smuggled message is delivered by the receiving server as though it arrived on
its own, but the connection that carried it belonged to the legitimate sending
domain. So SPF, DKIM and DMARC pass — for the outer envelope — while the inner
message claims any sender the attacker likes. That is arbitrary sender spoofing
with authentication intact, which is precisely what those mechanisms exist to
prevent. Disclosed in December 2023 and tracked as CVE-2023-51764 (Postfix),
CVE-2023-51765 (Sendmail) and CVE-2023-51766 (Exim).

**How this is tested without delivering mail.** The probe enters ``DATA`` and ends
the body with only the non-standard sequence, then waits. A server that is not
affected is still inside ``DATA``, says nothing, and the connection is closed —
which aborts the message, so nothing is ever queued. A server that *is* affected
answers ``250``, and only then has it accepted a message. To keep that case
harmless the recipient is a random, non-existent local part at the server's own
domain, so the accepted message has nowhere to go; and the standard terminator is
never sent.

The result is that a clean server receives no mail at all, and a vulnerable one
receives one undeliverable message. That is still mail-generating behaviour on a
production system, which is why the check is classified state-changing and runs
only in an explicitly aggressive scan.
"""
from __future__ import annotations

import asyncio
import logging
import re
import secrets
from dataclasses import dataclass
from typing import TYPE_CHECKING

from scanr.core.plugin_base import FindingData, PluginBase, PluginCategory, Severity

if TYPE_CHECKING:
    from scanr.core.context import ScanContext
    from scanr.models import Host

logger = logging.getLogger(__name__)

SMTP_PORTS = [25, 587, 2525]

_TIMEOUT = 8.0
# How long to wait for a 250 after the non-standard terminator. A server still in
# DATA mode says nothing, so this timeout is the negative result.
_EOD_WAIT = 5.0
_READ_LIMIT = 4096

_EHLO_NAME = "scanr-probe.invalid"


@dataclass(frozen=True)
class EodSequence:
    """A non-standard end-of-data sequence and what accepting it implies."""

    name: str
    raw: bytes
    note: str


# Ordered by how widely they were found to be accepted in the original research.
EOD_SEQUENCES: tuple[EodSequence, ...] = (
    EodSequence(
        name="<LF>.<LF>",
        raw=b"\n.\n",
        note="bare line feeds around the terminating dot",
    ),
    EodSequence(
        name="<CR>.<CR>",
        raw=b"\r.\r",
        note="bare carriage returns around the terminating dot",
    ),
    EodSequence(
        name="<CR><LF>.<CR>",
        raw=b"\r\n.\r",
        note="a standard opening but a bare CR closing the terminator",
    ),
    EodSequence(
        name="<LF>.<CR><LF>",
        raw=b"\n.\r\n",
        note="a bare LF opening the terminator",
    ),
)

_REPLY_RE = re.compile(rb"^(\d{3})", re.M)
_EHLO_DOMAIN_RE = re.compile(r"^220\s+(\S+)")


def reply_code(raw: bytes) -> int | None:
    """The numeric code of an SMTP reply, or None when nothing usable arrived."""
    if not raw:
        return None
    match = _REPLY_RE.search(raw)
    return int(match.group(1)) if match else None


def is_positive(code: int | None) -> bool:
    return code is not None and 200 <= code < 300


def server_domain(banner: str, fallback: str) -> str:
    """The domain to address the probe recipient at.

    The server's own greeting is preferred: a recipient at the host's own domain
    is the one most likely to be accepted at RCPT and least likely to leave the
    organisation if the server turns out to be affected.
    """
    match = _EHLO_DOMAIN_RE.match(banner.strip())
    if match:
        candidate = match.group(1).strip().rstrip(".")
        if "." in candidate and not candidate.replace(".", "").isdigit():
            return candidate
    return fallback


def build_probe_body(recipient: str, sequence: EodSequence) -> bytes:
    """A minimal message whose body ends with only the non-standard terminator."""
    headers = (
        f"From: <postmaster@{_EHLO_NAME}>\r\n"
        f"To: <{recipient}>\r\n"
        "Subject: ScanR authorized SMTP end-of-data conformance probe\r\n"
        "\r\n"
        "This message was generated by an authorized security scan to test whether\r\n"
        "this server accepts a non-standard SMTP end-of-data sequence. It is not\r\n"
        "expected to be delivered.\r\n"
    ).encode("ascii")
    # Deliberately no trailing \r\n.\r\n — only the sequence under test.
    return headers + sequence.raw


class SmtpSmugglingPlugin(PluginBase):
    id = "services.smtp_smuggling"
    name = "SMTP Smuggling (Non-Standard End-of-Data)"
    description = (
        "Detect SMTP servers that accept a non-standard end-of-data sequence, "
        "enabling message smuggling and SPF/DKIM-passing sender spoofing"
    )
    category = PluginCategory.services
    severity = Severity.medium
    cve_ids = ["CVE-2023-51764", "CVE-2023-51765", "CVE-2023-51766"]
    ports = SMTP_PORTS

    async def check(self, context: "ScanContext", host: "Host") -> list[FindingData]:
        findings: list[FindingData] = []
        for port in host.ports:
            if port.number not in SMTP_PORTS or port.state != "open":
                continue
            result = await self._test_sequences(host, port.number)
            if result is None:
                continue
            sequence, banner, recipient = result
            findings.append(
                self._build_finding(host.ip, port.number, sequence, banner, recipient)
            )
        return findings

    async def _test_sequences(
        self, host: "Host", port: int
    ) -> tuple[EodSequence, str, str] | None:
        """The first non-standard terminator the server accepted, if any.

        Each sequence needs its own connection, because accepting one ends the
        message. Testing stops at the first acceptance so an affected server
        receives one probe rather than four.
        """
        fallback = (getattr(host, "hostname", None) or host.ip).strip()
        for sequence in EOD_SEQUENCES:
            outcome = await self._probe(host.ip, port, sequence, fallback)
            if outcome is not None:
                banner, recipient = outcome
                return sequence, banner, recipient
        return None

    async def _probe(
        self, ip: str, port: int, sequence: EodSequence, fallback_domain: str
    ) -> tuple[str, str] | None:
        """(banner, recipient) when the server accepted `sequence`, else None."""
        writer = None
        try:
            reader, writer = await asyncio.wait_for(
                asyncio.open_connection(ip, port), timeout=_TIMEOUT
            )
            banner_raw = await asyncio.wait_for(reader.read(_READ_LIMIT), timeout=_TIMEOUT)
            if not is_positive(reply_code(banner_raw)):
                return None
            banner = banner_raw.decode("latin-1", errors="replace").strip()
            domain = server_domain(banner, fallback_domain)
            recipient = f"scanr-eod-probe-{secrets.token_hex(4)}@{domain}"

            if not await self._command(reader, writer, f"EHLO {_EHLO_NAME}"):
                # Fall back to HELO for a server that does not speak ESMTP.
                if not await self._command(reader, writer, f"HELO {_EHLO_NAME}"):
                    return None
            if not await self._command(reader, writer, "MAIL FROM:<>"):
                return None
            if not await self._command(reader, writer, f"RCPT TO:<{recipient}>"):
                # The server validates recipients, so DATA is unreachable and the
                # end-of-data behaviour cannot be observed. Report nothing rather
                # than guess.
                return None
            data_reply = await self._command(
                reader, writer, "DATA", expect_range=(300, 400)
            )
            if not data_reply:
                return None

            writer.write(build_probe_body(recipient, sequence))
            await asyncio.wait_for(writer.drain(), timeout=_TIMEOUT)

            # A server still inside DATA sends nothing here. Only an acceptance
            # produces a reply — and only then has a message been queued.
            try:
                raw = await asyncio.wait_for(reader.read(_READ_LIMIT), timeout=_EOD_WAIT)
            except asyncio.TimeoutError:
                return None
            if is_positive(reply_code(raw)):
                return banner, recipient
            return None
        except (OSError, asyncio.TimeoutError) as exc:
            logger.debug("SMTP smuggling probe failed %s:%d: %s", ip, port, exc)
            return None
        finally:
            if writer is not None:
                # Closing without sending the standard terminator aborts the
                # message on any server that did not already accept it.
                writer.close()
                try:
                    await writer.wait_closed()
                except (OSError, asyncio.TimeoutError):
                    pass

    @staticmethod
    async def _command(
        reader, writer, command: str, expect_range: tuple[int, int] = (200, 300)
    ) -> bool:
        writer.write(command.encode("ascii") + b"\r\n")
        await asyncio.wait_for(writer.drain(), timeout=_TIMEOUT)
        raw = await asyncio.wait_for(reader.read(_READ_LIMIT), timeout=_TIMEOUT)
        code = reply_code(raw)
        return code is not None and expect_range[0] <= code < expect_range[1]

    def _build_finding(
        self, ip: str, port: int, sequence: EodSequence, banner: str, recipient: str
    ) -> FindingData:
        return FindingData(
            plugin_id=self.id,
            severity=Severity.medium,
            title=f"SMTP Server Accepts Non-Standard End-of-Data ({sequence.name})",
            description=(
                f"The SMTP server on {ip}:{port} ended a message on the non-standard "
                f"sequence {sequence.name} — {sequence.note} — instead of requiring "
                "<CR><LF>.<CR><LF>. RFC 5321 defines exactly one end-of-data sequence, and "
                "accepting others is what makes SMTP smuggling possible.\n\n"
                "An attacker exploits the disagreement between two servers. They send one "
                "message through a provider whose outbound server passes the loose "
                "sequence through unchanged, with a second message hidden inside the body. "
                "This server treats the loose sequence as end-of-data, so it splits the "
                "transmission into two separate messages and delivers both.\n\n"
                "The consequence is spoofing that survives email authentication. The "
                "connection and the outer envelope belong to a legitimate sending domain, "
                "so SPF, DKIM and DMARC all pass — and the smuggled inner message, which "
                "recipients actually see, can claim any sender at all. That defeats the "
                "checks an organisation relies on to make internal-looking mail "
                "trustworthy, so it is a direct route to convincing phishing and business "
                "email compromise from an apparently verified sender."
            ),
            evidence=(
                f"Banner: {banner.splitlines()[0] if banner else '(none)'}\n"
                f"EHLO {_EHLO_NAME} → accepted\n"
                "MAIL FROM:<> → accepted\n"
                f"RCPT TO:<{recipient}> → accepted\n"
                "DATA → 354\n"
                f"Message body terminated with {sequence.name} only "
                f"({sequence.raw!r}), with no <CR><LF>.<CR><LF> sent.\n"
                "Server replied with a 2xx acceptance, so it treated the non-standard "
                "sequence as end-of-data.\n\n"
                "A conforming server would have remained in DATA mode and said nothing. "
                "The recipient local part is random and non-existent, so the accepted "
                "message is undeliverable."
            ),
            remediation=(
                "Update the MTA to a release that enforces the standard end-of-data "
                "sequence:\n"
                "  Postfix — 3.8.5 / 3.7.10 / 3.6.14 / 3.5.24 or later, and set "
                "'smtpd_forbid_bare_newline = yes' (with "
                "'smtpd_forbid_bare_newline_exclusions' for any legacy internal client "
                "that genuinely needs it)\n"
                "  Exim — 4.97.1 or later\n"
                "  Sendmail — apply the 'srv_features' / bare-newline configuration from "
                "the 8.18 advisory\n"
                "  Commercial and appliance MTAs — check the vendor's December 2023 "
                "SMTP smuggling advisory\n\n"
                "Then verify the whole path, not just this hop. Smuggling needs two "
                "servers to disagree, so an internet-facing gateway that is strict "
                "protects the internal MTAs behind it; conversely a strict internal server "
                "is bypassed if the gateway forwards bare newlines. Check any cloud mail "
                "filter or relay in front of this server too.\n\n"
                "Because this weakens sender authentication rather than replacing it, keep "
                "DMARC at 'p=reject' and continue to alert on internal-sender mail "
                "arriving from outside — that detection catches smuggled messages that a "
                "misconfigured hop elsewhere still lets through."
            ),
            references=[
                "https://sec-consult.com/blog/detail/smtp-smuggling-spoofing-e-mails-worldwide/",
                "https://nvd.nist.gov/vuln/detail/CVE-2023-51764",
                "https://www.postfix.org/smtp-smuggling.html",
            ],
            cve_ids=self.cve_ids,
            port_number=port,
            protocol="tcp",
            peer_review_command=(
                f"# see https://github.com/The-Login/SMTP-Smuggling-Tools (authorized use only)\n"
                f"swaks --server {ip}:{port} --quit-after RCPT --to postmaster@<domain>"
            ),
        )
